SHOP-14444: implemented flex-grid
zalora/global-scss pull request #17
Opened 2018-08-08 06:43 UTC by Yichang812

2018-08-17 04:31 UTC, winminsoe commented on _variables.scss
> +$white:       #fff;
why not use this? https://github.com/zalora/global-scss/blob/ee50c86b7aa94c14380f428d44e7a139f8fb3127/_variables.scss#L6

when doing the style guide, we wanted to follow the design pattern. Every Website have primary color and secondary color and so on. And the variable name should not reflect the actual colour.

2018-08-17 04:32 UTC, winminsoe commented on _variables.scss
> +$error:       #ba4242;
same for here. we should use the same error Color. No?. https://github.com/zalora/global-scss/blob/ee50c86b7aa94c14380f428d44e7a139f8fb3127/_variables.scss#L15

2018-08-29 07:28 UTC, penmanglewood requested changes

2018-08-29 07:28 UTC, penmanglewood commented on desktop/components/_forms.scss
> +    &.progressing {
How could this be empty?

2018-08-29 07:28 UTC, penmanglewood commented on desktop/components/_forms.scss
> +    border: 1px solid #00c8b4;
Indentation

2018-09-07 02:31 UTC, penmanglewood approved these changes

2018-09-07 02:31 UTC, merged