SHOP-13427: update FB white logo button
zalora/global-scss pull request #8
Opened 2017-06-20 12:25 UTC by thanhnguyennguyen

Hello @winminsoe ,
This pull request is to update Facebook button with a white logo as requirement mentioned in the ticket https://zalora.atlassian.net/browse/SHOP-13427
Please arrange your time help me review this change
Thank you

2017-06-20 12:27 UTC, thanhnguyennguyen commented
I will update new file at /images/local_mobile/svg_icons/icon_fb_white_logo.svg in shop repo

2017-06-20 15:46 UTC, winminsoe commented on desktop/components/_buttons.scss
> +        background-image: url("/images/local_mobile/svg_icons/icon_fb_white_logo.svg");
it shouldn't be `local_mobile`.

2017-06-20 15:47 UTC, winminsoe requested changes
Please check the comment.

2017-06-20 15:48 UTC, winminsoe commented
and if you are adding inside `svg_icons` folder, it will get included in sprite image/css also. do we need that?

2017-06-20 23:21 UTC, thanhnguyennguyen commented on desktop/components/_buttons.scss
> +        background-image: url("/images/local_mobile/svg_icons/icon_fb_white_logo.svg");
is it okay if I put it in /images/icon_fb_white_logo.svg ?
 I'm going to use it for both desktop and webmobile

2017-06-20 23:21 UTC, thanhnguyennguyen commented
is it okay if I put it in /images/icon_fb_white_logo.svg ?
I'm going to use it for both desktop and webmobile

2017-06-21 01:11 UTC, winminsoe commented
if it's for both, yes. you can put it outside of `local` or `local_mobile`.

2017-06-21 04:44 UTC, thanhnguyennguyen commented
I just updated this pull request.
Hi @winminsoe , 
Please arrange your time help me review again
Thanks

2017-06-21 05:15 UTC, merged